name: Check News and Notify Slack

on:
  schedule:
    - cron: '0 * * * *'  # 毎時実行
  workflow_dispatch:      # 手動実行用

jobs:
  check-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run news checker
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: python news_checker.py
